#!/bin/bash

echo "Hello. This is setup."

GPU_MEM=256

echo "Replace /boot/cmdline.txt"
echo "dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet" > "${mount}/boot/cmdline.txt"
cat "${mount}/boot/cmdline.txt"

echo "Replace /etc/fstab"
echo "proc            /proc           proc    defaults          0       0" > "${mount}/etc/fstab"
echo "/dev/mmcblk0p1  /boot           vfat    defaults          0       2" >> "${mount}/etc/fstab"
echo "/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1" >> "${mount}/etc/fstab"
cat "${mount}/etc/fstab"

cores=$(nproc)
echo "Number of processor cores: ${cores}"

echo "Checking disk space."
df -h

#rm /usr/lib/raspi-config/init_resize.sh
rm /etc/init.d/resize2fs_once
rm /etc/rc3.d/S01resize2fs_once

echo "Setting hostname."
echo "epOS" > /etc/hostname
cat /etc/hostname

echo "Setting gpu_mem."
if grep -q "gpu_mem" /boot/config.txt
then
    sed -i "s/gpu_mem.*/gpu_mem=${GPU_MEM}/" /boot/config.txt
else
    echo "gpu_mem=${GPU_MEM}" >> /boot/config.txt
fi
cat /boot/config.txt | grep "gpu_mem"

echo "Installing packages."
apt-get -y update
apt-get -y install git
apt-get -y install libhdf5-dev
apt-get –y install libhdf5-serial-dev
apt-get –y install libatlas-base-dev
apt-get -y install libjasper-dev
apt-get –y install libqtgui4
apt-get –y install libqt4-test
apt-get -y install python3
apt-get -y install python3-pip
apt-get -y install python-picamera python3-picamera python-rpi.gpio

pip3 install python-firebase
pip3 install firebase
pip3 install opencv-contrib-python==4.1.0.25

dpkg - -configure –a
apt-get install tesseract-ocr
pip3 install pytesseract
pip3 install pyttsx3
pip3 install imutils

sed -i "s/apt-get/apt-get -y/g" install_dependencies.sh

./install_dependencies.sh
make -j$(nproc) Release -C /home/pi/

echo "Run Python script."
python3 ./epOS_2.1.py

#echo "Downloading openFrameworks."
#cd /home/pi
#wget "${OF_URL}"
#mkdir openFrameworks
#tar vxfz "${OF_FILE}" -C openFrameworks --strip-components 1
#cd /home/pi/openFrameworks/scripts/linux/debian

#echo "Compiling polygonExample."
#cd /home/pi/openFrameworks/examples/graphics/polygonExample
#make -j$(nproc)

#echo "Setting up to run on boot."
#crontab -l > mycron
#echo "@reboot /home/pi/openFrameworks/examples/graphics/polygonExample/bin/polygonExample" >> mycron
#crontab mycron
#rm mycron

echo "Congratulations! Compiled version of openFrameworks $OF_VERSION has been setup!"
