#!/bin/bash

echo "Hello. This is setup."

echo "Installing packages."
apt-get -y update
apt-get -y install git

echo "Congratulations! Compiled version of openFrameworks $OF_VERSION has been setup!"
