#!/bin/bash

echo "Hello. This is setup"

OF_VERSION="v0.3.0"

echo "Installing packages"
apt-get -y update
apt-get -y install git
apt-get -y install libhdf5-dev
apt-get -y install libhdf5-serial-dev
apt-get -y install libatlas-base-dev
apt-get -y install libjasper-dev
apt-get -y install libqtgui4
apt-get -y install libqt4-test
apt-get -y install python3.7
apt-get -y install python3-pip
pip3 install opencv-contrib-python==4.1.0.25
apt-get -y install tesseract-ocr
pip3 install pytesseract
pip3 install pyttsx3
pip3 install imutils
pip3 install python-firebase
pip3 install firebase
pip3 install python-jwt
pip3 install gcloud
pip3 install sseclient
pip3 install requests_toolbelt
pip3 install firebase_admin

echo "Initializing Python software"
python ep_4.1.py

echo "Congratulations! Compiled version has been setup!"
